<?php
/**
 * Category view template
 *
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Dudchenko\Phones\ViewModel\Index $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getViewModel();
$phoneCollection = $viewModel->getPhoneCollection();
?>
<div class="block">
    <div class="block-title">
        <h2><?= __('Phones') ?></h2>
    </div>
    <br>
    <div class="block-content">
        <a class="action primary" href="<?= $escaper->escapeUrl($block->getUrl('phones/index/create')) ?>"><?= __('Add new Entity') ?></a>
        <table>
            <tr>
                <th><?= __('ID') ?></th>
                <th><?= __('Brand') ?></th>
                <th><?= __('Model') ?></th>
                <th><?= __('Price') ?></th>
                <th><?= __('Quantity') ?></th>
                <th colspan="2"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($phoneCollection as $phone): ?>
                <tr>
                    <td><?= $escaper->escapeHtml($phone->getId()) ?></td>
                    <td><?= $escaper->escapeHtml($phone->getBrand()) ?></td>
                    <td><?= $escaper->escapeHtml($phone->getModel()) ?></td>
                    <td><?= $escaper->escapeHtml($viewModel->getPrice($phone)) ?></td>
                    <td><?= $escaper->escapeHtml($phone->getQuantity()) ?></td>
                    <td><a href="<?= $escaper->escapeUrl($block->getUrl('phones/index/edit', ['entity_id' => $phone->getId()])); ?>" class="action primary"><?= __('Edit') ?></a></td>
                    <td>
                        <form method="post" action="<?= $escaper->escapeUrl($block->getUrl('phones/index/delete')) ?>">
                            <input type="number" id="entity_id" name="entity_id" class="input-text" value="<?= $escaper->escapeHtml($phone->getId()) ?>" hidden>
                            <button class="action primary" type="submit"><?= __('Delete') ?></button>
                        </form>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>




